# SPDX-License-Identifier: MIT

PROJ_ROOT ?= $(abspath ../..)
include $(PROJ_ROOT)/scripts/makefile.neorv32

.PHONY: test
test: size

JQ_TABLE_FILTER = \
	["Config","LUT6","FF"], ["------","----","--"], \
	( to_entries[] | [ .key, (.value.lut6|tostring), (.value.ff|tostring) ] ) \
	| @tsv

.PHONY: size
size: size_minimal size_lite size_standard size_full size_numa
	@echo "==="
	@jq -s '{minimal:.[0], lite:.[1], std:.[2], full:.[3], numa:.[4]}' \
		$(foreach f,$^,$(PROJ_ROOT)/build/size/$f.json) \
		> $(PROJ_ROOT)/build/size/size.json
	@jq -r '$(JQ_TABLE_FILTER)' $(PROJ_ROOT)/build/size/size.json
	@echo "==="

neorv32_build: neorv32-obj08.cf
neorv32-obj08.cf: $(NEORV32_SRCS)
	@mkdir -p $(PROJ_ROOT)/build/size && \
		cd $(PROJ_ROOT)/build/size && \
		ghdl -a --std=08 --work=neorv32 $(NEORV32_SRCS)

config_code = $(subst minimal,0,$(subst lite,1,$(subst standard,2,$(subst full,3,$(subst numa,4,$(strip $1))))))

size_%: neorv32_build force
	@mkdir -p $(PROJ_ROOT)/build/size && \
		cd $(PROJ_ROOT)/build/size && \
		CONFIG_CODE=$(call config_code,$*) CONFIG_NAME=$* \
			yosys -m ghdl -c $(PROJ_ROOT)/tests/size/yosys_synth.tcl

# Pattern-rules cannot be made PHONY. Force their rebuild by depending on this.
.PHONY: force
force:
	@
