# SPDX-License-Identifier: MIT

PROJ_ROOT ?= $(abspath ../..)
include $(PROJ_ROOT)/scripts/makefile.neorv32

.PHONY: test
test: bmc

.PHONY: bmc
bmc: gpio_vu

neorv32_build: neorv32-obj08.cf
neorv32-obj08.cf: $(NEORV32_SRCS)
	@mkdir -p $(PROJ_ROOT)/build/formal && \
		cd $(PROJ_ROOT)/build/formal && \
		ghdl -a --std=08 --work=neorv32 $(NEORV32_SRCS)

%_vu: force
	sby --yosys 'yosys -m ghdl' --prefix $(PROJ_ROOT)/build/formal/$* -f $*.sby bmc

# Pattern-rules cannot be made PHONY. Force their rebuild by depending on this.
.PHONY: force
force:
	@
