# SPDX-License-Identifier: MIT

PROJ_ROOT ?= $(abspath ../..)
include $(PROJ_ROOT)/scripts/makefile.neorv32

.PHONY: test
test: tool_questa

TOOL_ELAB_SRCS = $(abspath tool_elab_tb.vhd)
TOOL_SIM_SRCS = $(abspath tool_sim_tb.vhd)
TOOL_ELAB_TOP = tool_elab_tb
TOOL_SIM_TOP = tool_sim_tb
TOOL_FIRMWARE = $(abspath neorv32_firmware.hex)

.PHONY: tool_questa
tool_questa:
	@mkdir -p $(PROJ_ROOT)/build/tool/questa && \
		cd $(PROJ_ROOT)/build/tool/questa && \
		vcom -quiet -2008 -work neorv32 $(NEORV32_SRCS) && \
		vcom -quiet -2008 $(TOOL_ELAB_SRCS) $(TOOL_SIM_SRCS) && \
		cp $(TOOL_FIRMWARE) . && \
		vsim -quiet -c -do $(PROJ_ROOT)/scripts/tools/questa_test.tcl $(TOOL_SIM_TOP)

modelsim.ini:
	@vmap -quiet -c
	@vmap -quiet neorv32 work
