# SPDX-License-Identifier: MIT

PROJ_ROOT ?= $(abspath ../..)
include $(PROJ_ROOT)/scripts/makefile.neorv32

.PHONY: test
test: tool_nvc

TOOL_ELAB_SRCS = $(abspath tool_elab_tb.vhd)
TOOL_SIM_SRCS = $(abspath tool_sim_tb.vhd)
TOOL_ELAB_TOP = tool_elab_tb
TOOL_SIM_TOP = tool_sim_tb
TOOL_FIRMWARE = $(abspath neorv32_firmware.hex)

.PHONY: tool_nvc
tool_nvc:
	@mkdir -p $(PROJ_ROOT)/build/tool/nvc && \
		cd $(PROJ_ROOT)/build/tool/nvc && \
		nvc --std=08 -L. --work=neorv32 -a $(NEORV32_SRCS) && \
		nvc --std=08 -L. -a $(TOOL_ELAB_SRCS) $(TOOL_SIM_SRCS) && \
		cp $(TOOL_FIRMWARE) . && \
		nvc --std=08 -L. -e $(TOOL_SIM_TOP) -r --ieee-warnings=off
