# SPDX-License-Identifier: MIT

PROJ_ROOT ?= $(abspath ../..)
include $(PROJ_ROOT)/scripts/makefile.neorv32

.PHONY: test
test: unit

include makefile.units

.PHONY: unit
unit: $(UNIT_TOPS)

.PHONY: analyze
analyze:
	$(info Analyzing neorv32 sources and testbenches.)
	@mkdir -p $(PROJ_ROOT)/build/unit/ghdl && \
		cd $(PROJ_ROOT)/build/unit/ghdl && \
		ghdl -a --std=08 --work=neorv32 $(NEORV32_SRCS) && \
		ghdl -a --std=08 $(UNIT_SRCS)


%_tb: analyze force
	$(info Running testbench '$*'.)
	@mkdir -p $(PROJ_ROOT)/build/unit/ghdl && \
		cd $(PROJ_ROOT)/build/unit/ghdl && \
		ghdl -e --std=08 $@ && \
		ghdl -r --std=08 $@ --ieee-asserts=disable

# Pattern-rules cannot be made PHONY. Force their rebuild by depending on this.
.PHONY: force
force:
	@
