# SPDX-License-Identifier: MIT

UNIT_SRCS := $(abspath bus_pkg.vhd)
UNIT_TOPS :=

# Unit testbenches.
UNIT_SRCS += $(abspath gpio_tb.vhd)
UNIT_TOPS += gpio_tb

# Bus interface tests.
UNIT_SRCS += $(abspath bus_gpio_tb.vhd)
UNIT_TOPS += bus_gpio_tb
UNIT_SRCS += $(abspath bus_spi_tb.vhd)
UNIT_TOPS += bus_spi_tb
UNIT_SRCS += $(abspath bus_pwm_tb.vhd)
UNIT_TOPS += bus_pwm_tb
UNIT_SRCS += $(abspath bus_slink_tb.vhd)
UNIT_TOPS += bus_slink_tb
UNIT_SRCS += $(abspath bus_wdt_tb.vhd)
UNIT_TOPS += bus_wdt_tb
UNIT_SRCS += $(abspath bus_uart_tb.vhd)
UNIT_TOPS += bus_uart_tb
